services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
      # add port
      args:
        - PORT=5001
    image: ms-challenge-backend:latest
    pull_policy: build # This ensures it builds if not present
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5001
        - PORT=3000
    image: ms-challenge-frontend:latest
    pull_policy: build # This ensures it builds if not present
    ports:
      - "3000:3000" # Map the specified port
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
